# Generated by Django 2.2.14 on 2021-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='NULL', max_length=200)),
                ('password', models.CharField(default='NULL', max_length=50)),
                ('email', models.EmailField(default='NULL', max_length=200, unique=True)),
                ('phone', models.CharField(default='NULL', max_length=10, unique=True)),
            ],
        ),
    ]
