# Generated by Django 2.0 on 2020-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='NULL', max_length=200)),
                ('password', models.CharField(default='NULL', max_length=50)),
                ('email', models.EmailField(default='NULL', max_length=200)),
                ('phone', models.CharField(default='NULL', max_length=10)),
            ],
        ),
    ]
