# Generated by Django 2.0 on 2020-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200809_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
