# Generated by Django 2.0 on 2020-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200809_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(default='NULL', max_length=10, unique=True),
        ),
    ]
