# Generated by Django 2.0 on 2020-08-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_users_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='NULL', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.users'),
        ),
    ]
