# Generated by Django 2.0 on 2020-08-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200811_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(default='NULL', max_length=10, unique=True),
        ),
    ]
