# Generated by Django 2.0 on 2020-08-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_otp_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otp',
            new_name='otp_table',
        ),
    ]
