# Generated by Django 2.0 on 2020-08-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200811_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_table',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
