# Generated by Django 2.0 on 2020-08-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_otp_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp_table',
            name='user',
        ),
    ]
