# Generated by Django 2.0 on 2020-08-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_otp_table_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_json', models.CharField(default='NULL', max_length=200)),
                ('name', models.CharField(default='NULL', max_length=10, unique=True)),
                ('email', models.EmailField(default='NULL', max_length=200, unique=True)),
                ('address', models.CharField(default='NULL', max_length=200, unique=True)),
                ('pin', models.CharField(default='NULL', max_length=20, unique=True)),
                ('phone', models.CharField(default='NULL', max_length=10, unique=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.users')),
            ],
        ),
    ]
