# Generated by Django 2.0 on 2020-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='verified_emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='NULL', max_length=100, unique=True)),
                ('status', models.CharField(default='rendered', max_length=10)),
            ],
        ),
    ]
