# Generated by Django 2.0 on 2020-08-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_verified_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
