# Generated by Django 2.0 on 2020-08-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200818_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
