# Generated by Django 2.2.14 on 2021-04-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20210421_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.CustomUser'),
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
