# Generated by Django 2.2.14 on 2021-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='NULL', max_length=10)),
                ('phone', models.CharField(default='NULL', max_length=10, unique=True)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
    ]
