# Generated by Django 2.2.14 on 2021-04-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailverification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='verified_emails',
            new_name='UserEmail',
        ),
    ]
